import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from "react";
import Button from "rsuite/Button";
import NavBarInstance from "../component/NavbarInstance";

export default function Home(props) {
    console.log('props：', props);
    const [activeKey, setActiveKey] = useState(null);

    return (
        <div className={styles.layout}>

            <Head>
                <title>基于区块链的宠物流转系统</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <NavBarInstance appearance="subtle" activeKey={activeKey} onSelect={setActiveKey} />

            <main className={styles.container}>
                <div className={styles.col1}>
                    <div className={styles.textWrapper}>
                        <h1 className={styles.text1}>基于区块链的</h1>
                        <h1 className={styles.text1}>宠物流转系统</h1>
                    </div>
                    <div className={styles.textWrapper}>
                        <h3 className={styles.text2}>let us give a home</h3>
                        <h3 className={styles.text2}>to stroy pets</h3>
                    </div>
                    <div className={styles.buttonWrapper}>
                        <Button appearance="primary" block href={`/pets`}>
                            <p className={styles.text3}>立即领养</p>
                        </Button>
                    </div>
                </div>
                <div className={styles.col2}>
                    <Image className={styles.storeImg}
                           src="/index_pet.jpeg"
                           width={600}
                           height={360}
                           />
                </div>
            </main>

        </div>
    )
}
