import styles from "../../styles/applicationDetail.module.css";
import Head from "next/head";
import NavBarInstance from "../../component/NavbarInstance";
import React, {useState} from "react";
import List from "rsuite/List";
import Button from "rsuite/Button";

export async function getStaticProps(staticProps) {

    const id = staticProps.params.id;
    console.log({id});

    const res = await fetch(`${process.env.API_HOST}/api/applications/${id}`);
    const applicationData = await res.json();
    console.log({applicationData});

    return {
        props: {
            id,
            applicationData
        }
    }

}

export async function getStaticPaths() {

    const paths = [];
    return {
        paths,
        fallback: true
    }
}

const applicationDetail = (props) => {
    console.log(props.applicationData);
    // const {applicant, petId, timestamp} = props.applicationData;

    const [activeKey, setActiveKey] = useState(null);

    const handleAgress = () => {
        console.log('同意')
    };

    const handleDisagress = () => {
        console.log('不同意')
    };

    return (
        <div className={styles.layout}>

            <Head>
                <title>申请表</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <NavBarInstance appearance="subtle" activeKey={activeKey} onSelect={setActiveKey}/>

            <main className={styles.container}>
                {props.applicationData && (
                    <div>
                        <h3 className={styles.listText}>编号的{props.id}申请</h3><br/>
                        <List hover>
                            <List.Item key={props.applicationData.applicant}><p className={styles.listText}>申请人：{props.applicationData.applicant}</p></List.Item>
                            <List.Item key={props.applicationData.petId}><p className={styles.listText}>申请领养的宠物id：{props.applicationData.petId}</p></List.Item>
                            <List.Item key={props.applicationData.timestamp}><p className={styles.listText}>申请时间：{props.applicationData.timestamp}</p></List.Item>
                            <Button appearance="primary" block onClick={handleAgress}>
                                <p className={styles.text3}>同意</p>
                            </Button>
                            <Button appearance="primary" block onClick={handleDisagress}>
                                <p className={styles.text3}>拒绝</p>
                            </Button>
                        </List>
                    </div>
                )}
            </main>

        </div>
    )
};

export default applicationDetail;